### ISSUE TITLE
Slå sammen slett og endre dikt til en side

### ISSUE THREAD

**Issue by lrustand** [lrustand/http-server#8]
Lage en ny side som heter mine dikt der man har muligheten til å enten slette, endre, eller vise et av diktene til innlogget bruker.

**Comment by lrustand** [comment]
Mine dikt er lagt til i 45c55a3e8408ab4d3a8b5dd3fd8e2342ac825141. Må fortsatt få inn knapper for å endre og slette.

**Comment by lrustand** [comment]
Endre dikt er lagt til i 853cc0bb2d8e2f7a20c5b585d528f666274f63f2. Kun slett dikt som mangler. Fint om slett dikt poster direkte når man submitter så man slipper å velge diktet på nytt i slett_dikt og poste derifra.

EDIT: Hvis vi også legger til slett alle dikt i mine dikt så kan vi fjerne linken til slett_dikt fra headeren og fjerne lista fra slett_dikt siden.

**Comment by Nelde95** [comment]
Slett dikt lagt til i 8a1a428
